import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ToastContainer} from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import {AuthProvider} from './Providers'
// Add this import statement to your CSS or global styles file

import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '300',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
        {children}
        </AuthProvider>
        <ToastContainer/>
      </body>
    </html>
  )
}
